export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

// src 直下の layout.js は全てのフォルダに共通する layout を適用する
export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className="body-class"
                style={{
                    height: "100%",
                    background: "#00a896",
                }}
            >
                <p style={{ color: "white" }}>RootLayout</p>
                {children}
            </body>
        </html>
    );
}
